//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.Net.Units.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LengthUnit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LengthUnit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("More.Net.Units.Resources.LengthUnit", typeof(LengthUnit).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angstrom,Angstroms,Å.
        /// </summary>
        internal static string Angstrom {
            get {
                return ResourceManager.GetString("Angstrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter,Centimeters,cm.
        /// </summary>
        internal static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain,Chains.
        /// </summary>
        internal static string Chain {
            get {
                return ResourceManager.GetString("Chain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimeter,Decimeters,dm.
        /// </summary>
        internal static string Decimeter {
            get {
                return ResourceManager.GetString("Decimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femtometer,Femtometer,fm.
        /// </summary>
        internal static string Femtometer {
            get {
                return ResourceManager.GetString("Femtometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foot,Feet,ft,&apos;.
        /// </summary>
        internal static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furlong,Furlongs.
        /// </summary>
        internal static string Furlong {
            get {
                return ResourceManager.GetString("Furlong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch,Inches,in,&quot;.
        /// </summary>
        internal static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometer,Kilometers,km.
        /// </summary>
        internal static string Kilometer {
            get {
                return ResourceManager.GetString("Kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light-year,Light-years,ly.
        /// </summary>
        internal static string LightYear {
            get {
                return ResourceManager.GetString("LightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link,Links.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter,Meters,m.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrometer,Micrometers,µm.
        /// </summary>
        internal static string Micrometer {
            get {
                return ResourceManager.GetString("Micrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mile,Miles,mi.
        /// </summary>
        internal static string Mile {
            get {
                return ResourceManager.GetString("Mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeter,Millimeters,mm.
        /// </summary>
        internal static string Millimeter {
            get {
                return ResourceManager.GetString("Millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mil,Mils,mil;Thou,Thou,thou.
        /// </summary>
        internal static string Mils {
            get {
                return ResourceManager.GetString("Mils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanometer,Nanometers,nm.
        /// </summary>
        internal static string Nanometer {
            get {
                return ResourceManager.GetString("Nanometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nautical Mile,Nautical Miles,nmi.
        /// </summary>
        internal static string NauticalMile {
            get {
                return ResourceManager.GetString("NauticalMile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsec,Parsecs,pc.
        /// </summary>
        internal static string Parsec {
            get {
                return ResourceManager.GetString("Parsec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picometer,Picometers,pm.
        /// </summary>
        internal static string Picometer {
            get {
                return ResourceManager.GetString("Picometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rod,Rods.
        /// </summary>
        internal static string Rod {
            get {
                return ResourceManager.GetString("Rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenth,Tenths.
        /// </summary>
        internal static string Tenth {
            get {
                return ResourceManager.GetString("Tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yard,Yards,yd.
        /// </summary>
        internal static string Yard {
            get {
                return ResourceManager.GetString("Yard", resourceCulture);
            }
        }
    }
}
